os: linux
dist: focal
language: python
python:
  - 3.8
  
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get update -y
  - sudo apt-get install -y python-pytest
  - sudo pip install codecov
  - sudo apt install python3-pip
  
install:
  - sudo apt install software-properties-common
  - pip install coverage
  - pip install pytest-cov==2.11.1 
  - pip install pytest-cov pytest
  - pip install codecov
  - python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose

script:
  - python3 -m unittest test.py
